apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: server-pod-userservice
spec:
  maxReplicas: 5
  minReplicas: 1
  scaleTargetRef:
    apiVersion: extensions/v1beta1
    kind: Deployment
    name: server-pod-userservice
  targetCPUUtilizationPercentage: 20