apiVersion: v1
kind: Pod
metadata:
  name: server-pod-userservice
  labels:
    name: server-pod-userservice
    app: cluster-1

spec:
  containers:
    - name: server-pod-userservice
      image: avan4457/cluster-1
      ports:
        - containerPort: 5000
