apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: user-microservice
  name: user-microservice
spec:
  ports:
  - port: 5000
    protocol: TCP
    targetPort: 5000
  selector:
    app: user-microservice
status:
  loadBalancer: {}